### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by miro-ka** [ryantrinkle/memoise#1]
I have tried to install cabal and this is my output:

Resolving dependencies...
cabal: Could not resolve dependencies:
trying: memoise-0.9
rejecting: snaplet-postgresql-simple-0.4 (conflict: memoise =>
snaplet-postgresql-simple>=0.3 && <0.4)
trying: snaplet-postgresql-simple-0.3.0.3
trying: unordered-containers-0.2.3.0/installed-0c9...
trying: hashable-1.1.2.5/installed-e0f...
trying: errors-1.4.1/installed-44c...
trying: either-3.4/installed-d0b...
trying: semigroupoids-3.0.2/installed-88c...
trying: contravariant-0.4/installed-282...
rejecting: clientsession-0.9/installed-315..., 0.9 (conflict:
snaplet-postgresql-simple => clientsession>=0.7.2 && <0.9)
trying: clientsession-0.8.1
rejecting: skein-1.0.3/installed-a5c..., 1.0.3, 1.0.2, 1.0.1, 1.0.0 (conflict:
clientsession => skein>=0.1 && <0.2)
rejecting: skein-0.1.0.12, 0.1.0.11, 0.1.0.10, 0.1.0.9 (conflict:
contravariant => tagged==0.6/installed-cee..., skein => tagged>=0.2 && <0.5)
rejecting: skein-0.1.0.8, 0.1.0.7, 0.1.0.6, 0.1.0.5, 0.1.0.4, 0.1.0.3,
0.1.0.2, 0.1.0.1, 0.1 (conflict: hashable =>
bytestring==0.10.0.2/installed-bf7..., skein => bytestring>=0.9 && <0.10)

btw: thank you for the great video + sample

**Comment by ryantrinkle** [comment]
I just pushed a patch to each lesson that adds support for newer versions of Snap (up to 0.12.*).  I think this'll sort things out.  Let me know if you run into any other trouble!
